//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyMoney
    {
        public int Id { get; set; }
        public Nullable<int> TRANSACTION_ID { get; set; }
        public Nullable<int> DENOMINATION { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public Nullable<int> OPERATION { get; set; }
        public string CODE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
