//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PayPlus_LocalEntities : DbContext
    {
        public DB_PayPlus_LocalEntities()
            : base("name=DB_PayPlus_LocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackUpEcity> BackUpEcity { get; set; }
        public virtual DbSet<BackUpMoney> BackUpMoney { get; set; }
        public virtual DbSet<NotifyMoney> NotifyMoney { get; set; }
    }
}
