//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.WCFPcrfil2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFPcrfil2.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/estfil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode estfil(int tea_ext_l, int sal_ext_l, string fex_ext_l, int fun_ext_l, string fil_ext_l, string log_ext_l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/estfil", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> estfilAsync(int tea_ext_l, int sal_ext_l, string fex_ext_l, int fun_ext_l, string fil_ext_l, string log_ext_l);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WPProcinal.WCFPcrfil2.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WPProcinal.WCFPcrfil2.ServiceSoap>, WPProcinal.WCFPcrfil2.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode estfil(int tea_ext_l, int sal_ext_l, string fex_ext_l, int fun_ext_l, string fil_ext_l, string log_ext_l) {
            return base.Channel.estfil(tea_ext_l, sal_ext_l, fex_ext_l, fun_ext_l, fil_ext_l, log_ext_l);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> estfilAsync(int tea_ext_l, int sal_ext_l, string fex_ext_l, int fun_ext_l, string fil_ext_l, string log_ext_l) {
            return base.Channel.estfilAsync(tea_ext_l, sal_ext_l, fex_ext_l, fun_ext_l, fil_ext_l, log_ext_l);
        }
    }
}
