//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.WCFPayPad {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLSTransaction", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad")]
    [System.SerializableAttribute()]
    public partial class CLSTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaPagadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDCorresponsalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTramiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CedulaPagador {
            get {
                return this.CedulaPagadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaPagadorField, value) != true)) {
                    this.CedulaPagadorField = value;
                    this.RaisePropertyChanged("CedulaPagador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrato {
            get {
                return this.ContratoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContratoField, value) != true)) {
                    this.ContratoField = value;
                    this.RaisePropertyChanged("Contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaCuota {
            get {
                return this.FechaCuotaField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCuotaField, value) != true)) {
                    this.FechaCuotaField = value;
                    this.RaisePropertyChanged("FechaCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDCorresponsal {
            get {
                return this.IDCorresponsalField;
            }
            set {
                if ((this.IDCorresponsalField.Equals(value) != true)) {
                    this.IDCorresponsalField = value;
                    this.RaisePropertyChanged("IDCorresponsal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTramite {
            get {
                return this.IDTramiteField;
            }
            set {
                if ((this.IDTramiteField.Equals(value) != true)) {
                    this.IDTramiteField = value;
                    this.RaisePropertyChanged("IDTramite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia {
            get {
                return this.ReferenciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenciaField, value) != true)) {
                    this.ReferenciaField = value;
                    this.RaisePropertyChanged("Referencia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLSDatosTransaction", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad")]
    [System.SerializableAttribute()]
    public partial class CLSDatosTransaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorCuotaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTransaccion {
            get {
                return this.IDTransaccionField;
            }
            set {
                if ((this.IDTransaccionField.Equals(value) != true)) {
                    this.IDTransaccionField = value;
                    this.RaisePropertyChanged("IDTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoTransaccion {
            get {
                return this.TipoTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoTransaccionField, value) != true)) {
                    this.TipoTransaccionField = value;
                    this.RaisePropertyChanged("TipoTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ValorCuota {
            get {
                return this.ValorCuotaField;
            }
            set {
                if ((this.ValorCuotaField.Equals(value) != true)) {
                    this.ValorCuotaField = value;
                    this.RaisePropertyChanged("ValorCuota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLSEstado.EstadoAuditoria", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad")]
    public enum CLSEstadoEstadoAuditoria : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IniciandoTransaccion = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IngresandoBillete = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DevolviendoBillete = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ImprimiendoRecibo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorImprimiendo = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReciboImpreso = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FinalizandoTransaccion = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransaccionCancelada = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransaccionFallidad = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLSEstado.EstadoTransaction", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad")]
    public enum CLSEstadoEstadoTransaction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Iniciada = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aprobada = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pendiente = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelada = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fallida = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLSEstado.EstadoDetalle", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad")]
    public enum CLSEstadoEstadoDetalle : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ingresando = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Devolviendo = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLSTransactionDispenser", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad")]
    [System.SerializableAttribute()]
    public partial class CLSTransactionDispenser : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPagarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTransaccion {
            get {
                return this.IDTransaccionField;
            }
            set {
                if ((this.IDTransaccionField.Equals(value) != true)) {
                    this.IDTransaccionField = value;
                    this.RaisePropertyChanged("IDTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPagar {
            get {
                return this.TotalPagarField;
            }
            set {
                if ((this.TotalPagarField.Equals(value) != true)) {
                    this.TotalPagarField = value;
                    this.RaisePropertyChanged("TotalPagar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="sp_DatosTransaccionCM_Result", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad.EntityModels")]
    [System.SerializableAttribute()]
    public partial class sp_DatosTransaccionCM_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaPagadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDCompraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IDCorresponsalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDTransaccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CedulaPagador {
            get {
                return this.CedulaPagadorField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaPagadorField, value) != true)) {
                    this.CedulaPagadorField = value;
                    this.RaisePropertyChanged("CedulaPagador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaTransaccion {
            get {
                return this.FechaTransaccionField;
            }
            set {
                if ((this.FechaTransaccionField.Equals(value) != true)) {
                    this.FechaTransaccionField = value;
                    this.RaisePropertyChanged("FechaTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDCompra {
            get {
                return this.IDCompraField;
            }
            set {
                if ((object.ReferenceEquals(this.IDCompraField, value) != true)) {
                    this.IDCompraField = value;
                    this.RaisePropertyChanged("IDCompra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IDCorresponsal {
            get {
                return this.IDCorresponsalField;
            }
            set {
                if ((this.IDCorresponsalField.Equals(value) != true)) {
                    this.IDCorresponsalField = value;
                    this.RaisePropertyChanged("IDCorresponsal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDTransaccion {
            get {
                return this.IDTransaccionField;
            }
            set {
                if ((this.IDTransaccionField.Equals(value) != true)) {
                    this.IDTransaccionField = value;
                    this.RaisePropertyChanged("IDTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CLSDataControlScreen", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad.Clases")]
    [System.SerializableAttribute()]
    public partial class CLSDataControlScreen : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPProcinal.WCFPayPad.ClSMinDenomination[] ClSMinDenominationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxBaulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPProcinal.WCFPayPad.ClSMinDenomination[] ClSMinDenominations {
            get {
                return this.ClSMinDenominationsField;
            }
            set {
                if ((object.ReferenceEquals(this.ClSMinDenominationsField, value) != true)) {
                    this.ClSMinDenominationsField = value;
                    this.RaisePropertyChanged("ClSMinDenominations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxBaul {
            get {
                return this.MaxBaulField;
            }
            set {
                if ((this.MaxBaulField.Equals(value) != true)) {
                    this.MaxBaulField = value;
                    this.RaisePropertyChanged("MaxBaul");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClSMinDenomination", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad.Clases")]
    [System.SerializableAttribute()]
    public partial class ClSMinDenomination : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoProcinal", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad.Clases")]
    [System.SerializableAttribute()]
    public partial class InfoProcinal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPProcinal.WCFPayPad.TblDipMap DipMapField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPProcinal.WCFPayPad.TblSeat[] SeatsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPProcinal.WCFPayPad.TblDipMap DipMap {
            get {
                return this.DipMapField;
            }
            set {
                if ((object.ReferenceEquals(this.DipMapField, value) != true)) {
                    this.DipMapField = value;
                    this.RaisePropertyChanged("DipMap");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPProcinal.WCFPayPad.TblSeat[] Seats {
            get {
                return this.SeatsField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatsField, value) != true)) {
                    this.SeatsField = value;
                    this.RaisePropertyChanged("Seats");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblDipMap", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad.EntityModels")]
    [System.SerializableAttribute()]
    public partial class TblDipMap : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CinemaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HourFunctionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HourMillitarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MovieNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PointOfSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SecuenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TblDipMapIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CinemaId {
            get {
                return this.CinemaIdField;
            }
            set {
                if ((this.CinemaIdField.Equals(value) != true)) {
                    this.CinemaIdField = value;
                    this.RaisePropertyChanged("CinemaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date {
            get {
                return this.DateField;
            }
            set {
                if ((object.ReferenceEquals(this.DateField, value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateFormat {
            get {
                return this.DateFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.DateFormatField, value) != true)) {
                    this.DateFormatField = value;
                    this.RaisePropertyChanged("DateFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Day {
            get {
                return this.DayField;
            }
            set {
                if ((object.ReferenceEquals(this.DayField, value) != true)) {
                    this.DayField = value;
                    this.RaisePropertyChanged("Day");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DurationField, value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gener {
            get {
                return this.GenerField;
            }
            set {
                if ((object.ReferenceEquals(this.GenerField, value) != true)) {
                    this.GenerField = value;
                    this.RaisePropertyChanged("Gener");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Group {
            get {
                return this.GroupField;
            }
            set {
                if ((this.GroupField.Equals(value) != true)) {
                    this.GroupField = value;
                    this.RaisePropertyChanged("Group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Hour {
            get {
                return this.HourField;
            }
            set {
                if ((this.HourField.Equals(value) != true)) {
                    this.HourField = value;
                    this.RaisePropertyChanged("Hour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HourFunction {
            get {
                return this.HourFunctionField;
            }
            set {
                if ((object.ReferenceEquals(this.HourFunctionField, value) != true)) {
                    this.HourFunctionField = value;
                    this.RaisePropertyChanged("HourFunction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HourMillitar {
            get {
                return this.HourMillitarField;
            }
            set {
                if ((this.HourMillitarField.Equals(value) != true)) {
                    this.HourMillitarField = value;
                    this.RaisePropertyChanged("HourMillitar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IsCard {
            get {
                return this.IsCardField;
            }
            set {
                if ((object.ReferenceEquals(this.IsCardField, value) != true)) {
                    this.IsCardField = value;
                    this.RaisePropertyChanged("IsCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Letter {
            get {
                return this.LetterField;
            }
            set {
                if ((object.ReferenceEquals(this.LetterField, value) != true)) {
                    this.LetterField = value;
                    this.RaisePropertyChanged("Letter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MovieName {
            get {
                return this.MovieNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MovieNameField, value) != true)) {
                    this.MovieNameField = value;
                    this.RaisePropertyChanged("MovieName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PointOfSale {
            get {
                return this.PointOfSaleField;
            }
            set {
                if ((this.PointOfSaleField.Equals(value) != true)) {
                    this.PointOfSaleField = value;
                    this.RaisePropertyChanged("PointOfSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((this.RoomIdField.Equals(value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomName {
            get {
                return this.RoomNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNameField, value) != true)) {
                    this.RoomNameField = value;
                    this.RaisePropertyChanged("RoomName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Secuence {
            get {
                return this.SecuenceField;
            }
            set {
                if ((this.SecuenceField.Equals(value) != true)) {
                    this.SecuenceField = value;
                    this.RaisePropertyChanged("Secuence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TblDipMapId {
            get {
                return this.TblDipMapIdField;
            }
            set {
                if ((this.TblDipMapIdField.Equals(value) != true)) {
                    this.TblDipMapIdField = value;
                    this.RaisePropertyChanged("TblDipMapId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TblSeat", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad.EntityModels")]
    [System.SerializableAttribute()]
    public partial class TblSeat : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodTarifaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsReservedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecuenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TblDipMapIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TblSeatIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransactionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTarifa {
            get {
                return this.CodTarifaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodTarifaField, value) != true)) {
                    this.CodTarifaField = value;
                    this.RaisePropertyChanged("CodTarifa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsPay {
            get {
                return this.IsPayField;
            }
            set {
                if ((this.IsPayField.Equals(value) != true)) {
                    this.IsPayField = value;
                    this.RaisePropertyChanged("IsPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsReserved {
            get {
                return this.IsReservedField;
            }
            set {
                if ((this.IsReservedField.Equals(value) != true)) {
                    this.IsReservedField = value;
                    this.RaisePropertyChanged("IsReserved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Letter {
            get {
                return this.LetterField;
            }
            set {
                if ((object.ReferenceEquals(this.LetterField, value) != true)) {
                    this.LetterField = value;
                    this.RaisePropertyChanged("Letter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secuence {
            get {
                return this.SecuenceField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuenceField, value) != true)) {
                    this.SecuenceField = value;
                    this.RaisePropertyChanged("Secuence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TblDipMapId {
            get {
                return this.TblDipMapIdField;
            }
            set {
                if ((this.TblDipMapIdField.Equals(value) != true)) {
                    this.TblDipMapIdField = value;
                    this.RaisePropertyChanged("TblDipMapId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TblSeatId {
            get {
                return this.TblSeatIdField;
            }
            set {
                if ((this.TblSeatIdField.Equals(value) != true)) {
                    this.TblSeatIdField = value;
                    this.RaisePropertyChanged("TblSeatId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((this.TransactionIdField.Equals(value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/WCFPayPad")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.sp_DatosTransaccionCM_Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.TblDipMap))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.TblSeat[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.TblSeat))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.CLSTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.CLSDatosTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.CLSEstadoEstadoAuditoria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.CLSEstadoEstadoTransaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.CLSEstadoEstadoDetalle))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.CLSTransactionDispenser))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.CLSDataControlScreen))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.ClSMinDenomination[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.ClSMinDenomination))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WPProcinal.WCFPayPad.InfoProcinal))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccess {
            get {
                return this.IsSuccessField;
            }
            set {
                if ((this.IsSuccessField.Equals(value) != true)) {
                    this.IsSuccessField = value;
                    this.RaisePropertyChanged("IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFPayPad.IServicePayPad")]
    public interface IServicePayPad {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarTransaccion", ReplyAction="http://tempuri.org/IServicePayPad/InsertarTransaccionResponse")]
        int InsertarTransaccion(WPProcinal.WCFPayPad.CLSTransaction objTrasanction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarTransaccion", ReplyAction="http://tempuri.org/IServicePayPad/InsertarTransaccionResponse")]
        System.Threading.Tasks.Task<int> InsertarTransaccionAsync(WPProcinal.WCFPayPad.CLSTransaction objTrasanction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarTransaccionData", ReplyAction="http://tempuri.org/IServicePayPad/InsertarTransaccionDataResponse")]
        void InsertarTransaccionData(WPProcinal.WCFPayPad.CLSDatosTransaction objTrasanction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarTransaccionData", ReplyAction="http://tempuri.org/IServicePayPad/InsertarTransaccionDataResponse")]
        System.Threading.Tasks.Task InsertarTransaccionDataAsync(WPProcinal.WCFPayPad.CLSDatosTransaction objTrasanction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarAuditoria", ReplyAction="http://tempuri.org/IServicePayPad/InsertarAuditoriaResponse")]
        bool InsertarAuditoria(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoAuditoria IDEstadoAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarAuditoria", ReplyAction="http://tempuri.org/IServicePayPad/InsertarAuditoriaResponse")]
        System.Threading.Tasks.Task<bool> InsertarAuditoriaAsync(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoAuditoria IDEstadoAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ConsultaEstadoFactura", ReplyAction="http://tempuri.org/IServicePayPad/ConsultaEstadoFacturaResponse")]
        string ConsultaEstadoFactura(int IDCorresponsal, int IDTramite, string Referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ConsultaEstadoFactura", ReplyAction="http://tempuri.org/IServicePayPad/ConsultaEstadoFacturaResponse")]
        System.Threading.Tasks.Task<string> ConsultaEstadoFacturaAsync(int IDCorresponsal, int IDTramite, string Referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ActualizarEstadoTransaccion", ReplyAction="http://tempuri.org/IServicePayPad/ActualizarEstadoTransaccionResponse")]
        bool ActualizarEstadoTransaccion(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoTransaction IDEstadoAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ActualizarEstadoTransaccion", ReplyAction="http://tempuri.org/IServicePayPad/ActualizarEstadoTransaccionResponse")]
        System.Threading.Tasks.Task<bool> ActualizarEstadoTransaccionAsync(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoTransaction IDEstadoAuditoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertException", ReplyAction="http://tempuri.org/IServicePayPad/InsertExceptionResponse")]
        bool InsertException(int IDCorresponsal, string Exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertException", ReplyAction="http://tempuri.org/IServicePayPad/InsertExceptionResponse")]
        System.Threading.Tasks.Task<bool> InsertExceptionAsync(int IDCorresponsal, string Exception);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarDetalleTransaccion", ReplyAction="http://tempuri.org/IServicePayPad/InsertarDetalleTransaccionResponse")]
        bool InsertarDetalleTransaccion(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoDetalle Estado, decimal Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarDetalleTransaccion", ReplyAction="http://tempuri.org/IServicePayPad/InsertarDetalleTransaccionResponse")]
        System.Threading.Tasks.Task<bool> InsertarDetalleTransaccionAsync(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoDetalle Estado, decimal Valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarAlerta", ReplyAction="http://tempuri.org/IServicePayPad/InsertarAlertaResponse")]
        bool InsertarAlerta(string alerta, string sucursal, int idCorresponsal, string CreadoPor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarAlerta", ReplyAction="http://tempuri.org/IServicePayPad/InsertarAlertaResponse")]
        System.Threading.Tasks.Task<bool> InsertarAlertaAsync(string alerta, string sucursal, int idCorresponsal, string CreadoPor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/EnviarCorreo", ReplyAction="http://tempuri.org/IServicePayPad/EnviarCorreoResponse")]
        bool EnviarCorreo(string mensaje, string sucursal, int idCorresponsal, string CreadoPor, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/EnviarCorreo", ReplyAction="http://tempuri.org/IServicePayPad/EnviarCorreoResponse")]
        System.Threading.Tasks.Task<bool> EnviarCorreoAsync(string mensaje, string sucursal, int idCorresponsal, string CreadoPor, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/EnviarCorreoV2", ReplyAction="http://tempuri.org/IServicePayPad/EnviarCorreoV2Response")]
        bool EnviarCorreoV2(string email, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/EnviarCorreoV2", ReplyAction="http://tempuri.org/IServicePayPad/EnviarCorreoV2Response")]
        System.Threading.Tasks.Task<bool> EnviarCorreoV2Async(string email, string asunto, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarControlBillete", ReplyAction="http://tempuri.org/IServicePayPad/InsertarControlBilleteResponse")]
        bool InsertarControlBillete(int idCorresponsal, int idDenominacion, bool Baul, bool Eliminado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarControlBillete", ReplyAction="http://tempuri.org/IServicePayPad/InsertarControlBilleteResponse")]
        System.Threading.Tasks.Task<bool> InsertarControlBilleteAsync(int idCorresponsal, int idDenominacion, bool Baul, bool Eliminado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarControlMonedas", ReplyAction="http://tempuri.org/IServicePayPad/InsertarControlMonedasResponse")]
        System.Data.DataSet InsertarControlMonedas(int idDenominacion, int idCorresponsal, int operacion, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarControlMonedas", ReplyAction="http://tempuri.org/IServicePayPad/InsertarControlMonedasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> InsertarControlMonedasAsync(int idDenominacion, int idCorresponsal, int operacion, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarControlDispenser", ReplyAction="http://tempuri.org/IServicePayPad/InsertarControlDispenserResponse")]
        System.Data.DataSet InsertarControlDispenser(int idDenominacion, int idCorresponsal, int operacion, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarControlDispenser", ReplyAction="http://tempuri.org/IServicePayPad/InsertarControlDispenserResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> InsertarControlDispenserAsync(int idDenominacion, int idCorresponsal, int operacion, int cantidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ActualizacionArqueo", ReplyAction="http://tempuri.org/IServicePayPad/ActualizacionArqueoResponse")]
        void ActualizacionArqueo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ActualizacionArqueo", ReplyAction="http://tempuri.org/IServicePayPad/ActualizacionArqueoResponse")]
        System.Threading.Tasks.Task ActualizacionArqueoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ConteoBaul", ReplyAction="http://tempuri.org/IServicePayPad/ConteoBaulResponse")]
        int ConteoBaul();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ConteoBaul", ReplyAction="http://tempuri.org/IServicePayPad/ConteoBaulResponse")]
        System.Threading.Tasks.Task<int> ConteoBaulAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarControlAlarma", ReplyAction="http://tempuri.org/IServicePayPad/InsertarControlAlarmaResponse")]
        bool InsertarControlAlarma(System.DateTime FechaInicio, System.DateTime FechaFin, string CreadoPor, int idCorresponsal, int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarControlAlarma", ReplyAction="http://tempuri.org/IServicePayPad/InsertarControlAlarmaResponse")]
        System.Threading.Tasks.Task<bool> InsertarControlAlarmaAsync(System.DateTime FechaInicio, System.DateTime FechaFin, string CreadoPor, int idCorresponsal, int idEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ConsultarTransaccionesUsuario", ReplyAction="http://tempuri.org/IServicePayPad/ConsultarTransaccionesUsuarioResponse")]
        int ConsultarTransaccionesUsuario(string cedula, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ConsultarTransaccionesUsuario", ReplyAction="http://tempuri.org/IServicePayPad/ConsultarTransaccionesUsuarioResponse")]
        System.Threading.Tasks.Task<int> ConsultarTransaccionesUsuarioAsync(string cedula, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ConsultarEstadoReferencia", ReplyAction="http://tempuri.org/IServicePayPad/ConsultarEstadoReferenciaResponse")]
        string ConsultarEstadoReferencia(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ConsultarEstadoReferencia", ReplyAction="http://tempuri.org/IServicePayPad/ConsultarEstadoReferenciaResponse")]
        System.Threading.Tasks.Task<string> ConsultarEstadoReferenciaAsync(string referencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarTransaccionDispenser", ReplyAction="http://tempuri.org/IServicePayPad/InsertarTransaccionDispenserResponse")]
        void InsertarTransaccionDispenser(WPProcinal.WCFPayPad.CLSTransactionDispenser datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarTransaccionDispenser", ReplyAction="http://tempuri.org/IServicePayPad/InsertarTransaccionDispenserResponse")]
        System.Threading.Tasks.Task InsertarTransaccionDispenserAsync(WPProcinal.WCFPayPad.CLSTransactionDispenser datos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ActualizarTransaccionDispenser", ReplyAction="http://tempuri.org/IServicePayPad/ActualizarTransaccionDispenserResponse")]
        void ActualizarTransaccionDispenser(int idTransaccion, decimal valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ActualizarTransaccionDispenser", ReplyAction="http://tempuri.org/IServicePayPad/ActualizarTransaccionDispenserResponse")]
        System.Threading.Tasks.Task ActualizarTransaccionDispenserAsync(int idTransaccion, decimal valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/BilletesBaul", ReplyAction="http://tempuri.org/IServicePayPad/BilletesBaulResponse")]
        int BilletesBaul(int idCorresponsal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/BilletesBaul", ReplyAction="http://tempuri.org/IServicePayPad/BilletesBaulResponse")]
        System.Threading.Tasks.Task<int> BilletesBaulAsync(int idCorresponsal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ReiniciarBaul", ReplyAction="http://tempuri.org/IServicePayPad/ReiniciarBaulResponse")]
        void ReiniciarBaul(int idCorresponsal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/ReiniciarBaul", ReplyAction="http://tempuri.org/IServicePayPad/ReiniciarBaulResponse")]
        System.Threading.Tasks.Task ReiniciarBaulAsync(int idCorresponsal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/DatosTransaccionCM", ReplyAction="http://tempuri.org/IServicePayPad/DatosTransaccionCMResponse")]
        WPProcinal.WCFPayPad.sp_DatosTransaccionCM_Result DatosTransaccionCM(string idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/DatosTransaccionCM", ReplyAction="http://tempuri.org/IServicePayPad/DatosTransaccionCMResponse")]
        System.Threading.Tasks.Task<WPProcinal.WCFPayPad.sp_DatosTransaccionCM_Result> DatosTransaccionCMAsync(string idCompra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/GetDataControlScreen", ReplyAction="http://tempuri.org/IServicePayPad/GetDataControlScreenResponse")]
        WPProcinal.WCFPayPad.CLSDataControlScreen GetDataControlScreen(int correspondentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/GetDataControlScreen", ReplyAction="http://tempuri.org/IServicePayPad/GetDataControlScreenResponse")]
        System.Threading.Tasks.Task<WPProcinal.WCFPayPad.CLSDataControlScreen> GetDataControlScreenAsync(int correspondentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarTransaccionCotrafa", ReplyAction="http://tempuri.org/IServicePayPad/InsertarTransaccionCotrafaResponse")]
        int InsertarTransaccionCotrafa(WPProcinal.WCFPayPad.CLSTransaction objTrasanction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertarTransaccionCotrafa", ReplyAction="http://tempuri.org/IServicePayPad/InsertarTransaccionCotrafaResponse")]
        System.Threading.Tasks.Task<int> InsertarTransaccionCotrafaAsync(WPProcinal.WCFPayPad.CLSTransaction objTrasanction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertDataProcinal", ReplyAction="http://tempuri.org/IServicePayPad/InsertDataProcinalResponse")]
        WPProcinal.WCFPayPad.Response InsertDataProcinal(WPProcinal.WCFPayPad.InfoProcinal infoProcinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/InsertDataProcinal", ReplyAction="http://tempuri.org/IServicePayPad/InsertDataProcinalResponse")]
        System.Threading.Tasks.Task<WPProcinal.WCFPayPad.Response> InsertDataProcinalAsync(WPProcinal.WCFPayPad.InfoProcinal infoProcinal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/GetDataReceiptProcinal", ReplyAction="http://tempuri.org/IServicePayPad/GetDataReceiptProcinalResponse")]
        string GetDataReceiptProcinal(int correspondentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePayPad/GetDataReceiptProcinal", ReplyAction="http://tempuri.org/IServicePayPad/GetDataReceiptProcinalResponse")]
        System.Threading.Tasks.Task<string> GetDataReceiptProcinalAsync(int correspondentId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePayPadChannel : WPProcinal.WCFPayPad.IServicePayPad, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePayPadClient : System.ServiceModel.ClientBase<WPProcinal.WCFPayPad.IServicePayPad>, WPProcinal.WCFPayPad.IServicePayPad {
        
        public ServicePayPadClient() {
        }
        
        public ServicePayPadClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePayPadClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePayPadClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePayPadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertarTransaccion(WPProcinal.WCFPayPad.CLSTransaction objTrasanction) {
            return base.Channel.InsertarTransaccion(objTrasanction);
        }
        
        public System.Threading.Tasks.Task<int> InsertarTransaccionAsync(WPProcinal.WCFPayPad.CLSTransaction objTrasanction) {
            return base.Channel.InsertarTransaccionAsync(objTrasanction);
        }
        
        public void InsertarTransaccionData(WPProcinal.WCFPayPad.CLSDatosTransaction objTrasanction) {
            base.Channel.InsertarTransaccionData(objTrasanction);
        }
        
        public System.Threading.Tasks.Task InsertarTransaccionDataAsync(WPProcinal.WCFPayPad.CLSDatosTransaction objTrasanction) {
            return base.Channel.InsertarTransaccionDataAsync(objTrasanction);
        }
        
        public bool InsertarAuditoria(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoAuditoria IDEstadoAuditoria) {
            return base.Channel.InsertarAuditoria(IDTransaccion, IDEstadoAuditoria);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAuditoriaAsync(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoAuditoria IDEstadoAuditoria) {
            return base.Channel.InsertarAuditoriaAsync(IDTransaccion, IDEstadoAuditoria);
        }
        
        public string ConsultaEstadoFactura(int IDCorresponsal, int IDTramite, string Referencia) {
            return base.Channel.ConsultaEstadoFactura(IDCorresponsal, IDTramite, Referencia);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaEstadoFacturaAsync(int IDCorresponsal, int IDTramite, string Referencia) {
            return base.Channel.ConsultaEstadoFacturaAsync(IDCorresponsal, IDTramite, Referencia);
        }
        
        public bool ActualizarEstadoTransaccion(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoTransaction IDEstadoAuditoria) {
            return base.Channel.ActualizarEstadoTransaccion(IDTransaccion, IDEstadoAuditoria);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarEstadoTransaccionAsync(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoTransaction IDEstadoAuditoria) {
            return base.Channel.ActualizarEstadoTransaccionAsync(IDTransaccion, IDEstadoAuditoria);
        }
        
        public bool InsertException(int IDCorresponsal, string Exception) {
            return base.Channel.InsertException(IDCorresponsal, Exception);
        }
        
        public System.Threading.Tasks.Task<bool> InsertExceptionAsync(int IDCorresponsal, string Exception) {
            return base.Channel.InsertExceptionAsync(IDCorresponsal, Exception);
        }
        
        public bool InsertarDetalleTransaccion(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoDetalle Estado, decimal Valor) {
            return base.Channel.InsertarDetalleTransaccion(IDTransaccion, Estado, Valor);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarDetalleTransaccionAsync(int IDTransaccion, WPProcinal.WCFPayPad.CLSEstadoEstadoDetalle Estado, decimal Valor) {
            return base.Channel.InsertarDetalleTransaccionAsync(IDTransaccion, Estado, Valor);
        }
        
        public bool InsertarAlerta(string alerta, string sucursal, int idCorresponsal, string CreadoPor) {
            return base.Channel.InsertarAlerta(alerta, sucursal, idCorresponsal, CreadoPor);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAlertaAsync(string alerta, string sucursal, int idCorresponsal, string CreadoPor) {
            return base.Channel.InsertarAlertaAsync(alerta, sucursal, idCorresponsal, CreadoPor);
        }
        
        public bool EnviarCorreo(string mensaje, string sucursal, int idCorresponsal, string CreadoPor, string email) {
            return base.Channel.EnviarCorreo(mensaje, sucursal, idCorresponsal, CreadoPor, email);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarCorreoAsync(string mensaje, string sucursal, int idCorresponsal, string CreadoPor, string email) {
            return base.Channel.EnviarCorreoAsync(mensaje, sucursal, idCorresponsal, CreadoPor, email);
        }
        
        public bool EnviarCorreoV2(string email, string asunto, string mensaje) {
            return base.Channel.EnviarCorreoV2(email, asunto, mensaje);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarCorreoV2Async(string email, string asunto, string mensaje) {
            return base.Channel.EnviarCorreoV2Async(email, asunto, mensaje);
        }
        
        public bool InsertarControlBillete(int idCorresponsal, int idDenominacion, bool Baul, bool Eliminado) {
            return base.Channel.InsertarControlBillete(idCorresponsal, idDenominacion, Baul, Eliminado);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarControlBilleteAsync(int idCorresponsal, int idDenominacion, bool Baul, bool Eliminado) {
            return base.Channel.InsertarControlBilleteAsync(idCorresponsal, idDenominacion, Baul, Eliminado);
        }
        
        public System.Data.DataSet InsertarControlMonedas(int idDenominacion, int idCorresponsal, int operacion, int cantidad) {
            return base.Channel.InsertarControlMonedas(idDenominacion, idCorresponsal, operacion, cantidad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InsertarControlMonedasAsync(int idDenominacion, int idCorresponsal, int operacion, int cantidad) {
            return base.Channel.InsertarControlMonedasAsync(idDenominacion, idCorresponsal, operacion, cantidad);
        }
        
        public System.Data.DataSet InsertarControlDispenser(int idDenominacion, int idCorresponsal, int operacion, int cantidad) {
            return base.Channel.InsertarControlDispenser(idDenominacion, idCorresponsal, operacion, cantidad);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> InsertarControlDispenserAsync(int idDenominacion, int idCorresponsal, int operacion, int cantidad) {
            return base.Channel.InsertarControlDispenserAsync(idDenominacion, idCorresponsal, operacion, cantidad);
        }
        
        public void ActualizacionArqueo() {
            base.Channel.ActualizacionArqueo();
        }
        
        public System.Threading.Tasks.Task ActualizacionArqueoAsync() {
            return base.Channel.ActualizacionArqueoAsync();
        }
        
        public int ConteoBaul() {
            return base.Channel.ConteoBaul();
        }
        
        public System.Threading.Tasks.Task<int> ConteoBaulAsync() {
            return base.Channel.ConteoBaulAsync();
        }
        
        public bool InsertarControlAlarma(System.DateTime FechaInicio, System.DateTime FechaFin, string CreadoPor, int idCorresponsal, int idEstado) {
            return base.Channel.InsertarControlAlarma(FechaInicio, FechaFin, CreadoPor, idCorresponsal, idEstado);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarControlAlarmaAsync(System.DateTime FechaInicio, System.DateTime FechaFin, string CreadoPor, int idCorresponsal, int idEstado) {
            return base.Channel.InsertarControlAlarmaAsync(FechaInicio, FechaFin, CreadoPor, idCorresponsal, idEstado);
        }
        
        public int ConsultarTransaccionesUsuario(string cedula, System.DateTime fecha) {
            return base.Channel.ConsultarTransaccionesUsuario(cedula, fecha);
        }
        
        public System.Threading.Tasks.Task<int> ConsultarTransaccionesUsuarioAsync(string cedula, System.DateTime fecha) {
            return base.Channel.ConsultarTransaccionesUsuarioAsync(cedula, fecha);
        }
        
        public string ConsultarEstadoReferencia(string referencia) {
            return base.Channel.ConsultarEstadoReferencia(referencia);
        }
        
        public System.Threading.Tasks.Task<string> ConsultarEstadoReferenciaAsync(string referencia) {
            return base.Channel.ConsultarEstadoReferenciaAsync(referencia);
        }
        
        public void InsertarTransaccionDispenser(WPProcinal.WCFPayPad.CLSTransactionDispenser datos) {
            base.Channel.InsertarTransaccionDispenser(datos);
        }
        
        public System.Threading.Tasks.Task InsertarTransaccionDispenserAsync(WPProcinal.WCFPayPad.CLSTransactionDispenser datos) {
            return base.Channel.InsertarTransaccionDispenserAsync(datos);
        }
        
        public void ActualizarTransaccionDispenser(int idTransaccion, decimal valor) {
            base.Channel.ActualizarTransaccionDispenser(idTransaccion, valor);
        }
        
        public System.Threading.Tasks.Task ActualizarTransaccionDispenserAsync(int idTransaccion, decimal valor) {
            return base.Channel.ActualizarTransaccionDispenserAsync(idTransaccion, valor);
        }
        
        public int BilletesBaul(int idCorresponsal) {
            return base.Channel.BilletesBaul(idCorresponsal);
        }
        
        public System.Threading.Tasks.Task<int> BilletesBaulAsync(int idCorresponsal) {
            return base.Channel.BilletesBaulAsync(idCorresponsal);
        }
        
        public void ReiniciarBaul(int idCorresponsal) {
            base.Channel.ReiniciarBaul(idCorresponsal);
        }
        
        public System.Threading.Tasks.Task ReiniciarBaulAsync(int idCorresponsal) {
            return base.Channel.ReiniciarBaulAsync(idCorresponsal);
        }
        
        public WPProcinal.WCFPayPad.sp_DatosTransaccionCM_Result DatosTransaccionCM(string idCompra) {
            return base.Channel.DatosTransaccionCM(idCompra);
        }
        
        public System.Threading.Tasks.Task<WPProcinal.WCFPayPad.sp_DatosTransaccionCM_Result> DatosTransaccionCMAsync(string idCompra) {
            return base.Channel.DatosTransaccionCMAsync(idCompra);
        }
        
        public WPProcinal.WCFPayPad.CLSDataControlScreen GetDataControlScreen(int correspondentId) {
            return base.Channel.GetDataControlScreen(correspondentId);
        }
        
        public System.Threading.Tasks.Task<WPProcinal.WCFPayPad.CLSDataControlScreen> GetDataControlScreenAsync(int correspondentId) {
            return base.Channel.GetDataControlScreenAsync(correspondentId);
        }
        
        public int InsertarTransaccionCotrafa(WPProcinal.WCFPayPad.CLSTransaction objTrasanction) {
            return base.Channel.InsertarTransaccionCotrafa(objTrasanction);
        }
        
        public System.Threading.Tasks.Task<int> InsertarTransaccionCotrafaAsync(WPProcinal.WCFPayPad.CLSTransaction objTrasanction) {
            return base.Channel.InsertarTransaccionCotrafaAsync(objTrasanction);
        }
        
        public WPProcinal.WCFPayPad.Response InsertDataProcinal(WPProcinal.WCFPayPad.InfoProcinal infoProcinal) {
            return base.Channel.InsertDataProcinal(infoProcinal);
        }
        
        public System.Threading.Tasks.Task<WPProcinal.WCFPayPad.Response> InsertDataProcinalAsync(WPProcinal.WCFPayPad.InfoProcinal infoProcinal) {
            return base.Channel.InsertDataProcinalAsync(infoProcinal);
        }
        
        public string GetDataReceiptProcinal(int correspondentId) {
            return base.Channel.GetDataReceiptProcinal(correspondentId);
        }
        
        public System.Threading.Tasks.Task<string> GetDataReceiptProcinalAsync(int correspondentId) {
            return base.Channel.GetDataReceiptProcinalAsync(correspondentId);
        }
    }
}
