//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.WCFReembolso {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFReembolso.reembolsoSoap")]
    public interface reembolsoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comint", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode comint(double teatro, double punto, string fecha_reembolso, double secuencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/comint", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> comintAsync(double teatro, double punto, string fecha_reembolso, double secuencia);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface reembolsoSoapChannel : WPProcinal.WCFReembolso.reembolsoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class reembolsoSoapClient : System.ServiceModel.ClientBase<WPProcinal.WCFReembolso.reembolsoSoap>, WPProcinal.WCFReembolso.reembolsoSoap {
        
        public reembolsoSoapClient() {
        }
        
        public reembolsoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public reembolsoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public reembolsoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public reembolsoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode comint(double teatro, double punto, string fecha_reembolso, double secuencia) {
            return base.Channel.comint(teatro, punto, fecha_reembolso, secuencia);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> comintAsync(double teatro, double punto, string fecha_reembolso, double secuencia) {
            return base.Channel.comintAsync(teatro, punto, fecha_reembolso, secuencia);
        }
    }
}
