//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.WCFReserva {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFReserva.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/resgru", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode resgru(int tea_ext_l, double pun_ext_l, double sal_ext_l, string fex_ext_l, double fun_ext_l, string fil_ext_l, double col_ext_l, double gru_ext_l, double sec_ext_l, double pel_ext_l, string tip_ext_l, string cor_ext_l, double tr1_ext_l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/resgru", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> resgruAsync(int tea_ext_l, double pun_ext_l, double sal_ext_l, string fex_ext_l, double fun_ext_l, string fil_ext_l, double col_ext_l, double gru_ext_l, double sec_ext_l, double pel_ext_l, string tip_ext_l, string cor_ext_l, double tr1_ext_l);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WPProcinal.WCFReserva.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WPProcinal.WCFReserva.ServiceSoap>, WPProcinal.WCFReserva.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode resgru(int tea_ext_l, double pun_ext_l, double sal_ext_l, string fex_ext_l, double fun_ext_l, string fil_ext_l, double col_ext_l, double gru_ext_l, double sec_ext_l, double pel_ext_l, string tip_ext_l, string cor_ext_l, double tr1_ext_l) {
            return base.Channel.resgru(tea_ext_l, pun_ext_l, sal_ext_l, fex_ext_l, fun_ext_l, fil_ext_l, col_ext_l, gru_ext_l, sec_ext_l, pel_ext_l, tip_ext_l, cor_ext_l, tr1_ext_l);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> resgruAsync(int tea_ext_l, double pun_ext_l, double sal_ext_l, string fex_ext_l, double fun_ext_l, string fil_ext_l, double col_ext_l, double gru_ext_l, double sec_ext_l, double pel_ext_l, string tip_ext_l, string cor_ext_l, double tr1_ext_l) {
            return base.Channel.resgruAsync(tea_ext_l, pun_ext_l, sal_ext_l, fex_ext_l, fun_ext_l, fil_ext_l, col_ext_l, gru_ext_l, sec_ext_l, pel_ext_l, tip_ext_l, cor_ext_l, tr1_ext_l);
        }
    }
}
