//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyPay
    {
        public int Id { get; set; }
        public Nullable<int> STATE_TRANSACTION_ID { get; set; }
        public Nullable<System.DateTime> DATE_END { get; set; }
        public Nullable<decimal> INCOME_AMOUNT { get; set; }
        public Nullable<decimal> RETURN_AMOUNT { get; set; }
        public Nullable<int> TRANSACTION_ID { get; set; }
    }
}
