//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.ADO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBProcinalEntities : DbContext
    {
        public DBProcinalEntities()
            : base("name=DBProcinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblDipMap> TblDipMaps { get; set; }
        public virtual DbSet<TblTypeSeat> TblTypeSeats { get; set; }
        public virtual DbSet<TblPay> TblPays { get; set; }
    }
}
