//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class RePrint
    {
        public int Id { get; set; }
        public string Cinema { get; set; }
        public string Movie { get; set; }
        public string Time { get; set; }
        public string Room { get; set; }
        public string Date { get; set; }
        public string Seat { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Tramite { get; set; }
        public string Category { get; set; }
        public string Consecutivo { get; set; }
        public string Secuencia { get; set; }
        public string Formato { get; set; }
        public Nullable<int> IDTransaccion { get; set; }
    }
}
