//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblDipMap
    {
        public int DipMapId { get; set; }
        public Nullable<int> CinemaId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string Date { get; set; }
        public string DateFormat { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> HourFormat { get; set; }
        public string Letter { get; set; }
        public string Login { get; set; }
        public Nullable<int> MovieId { get; set; }
        public Nullable<int> PointOfSale { get; set; }
        public Nullable<int> Group { get; set; }
        public Nullable<int> Secuence { get; set; }
        public string IsCard { get; set; }
        public string MovieName { get; set; }
        public string Language { get; set; }
        public string Gener { get; set; }
        public string Duration { get; set; }
        public string Day { get; set; }
        public string HourFunction { get; set; }
        public string RoomName { get; set; }
        public string Category { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
