//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPay
    {
        public int TblPayId { get; set; }
        public Nullable<int> DipMapId { get; set; }
        public Nullable<bool> IsPay { get; set; }
    }
}
