//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTypeSeat
    {
        public int TblTypeSeat1 { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Letter { get; set; }
        public string Number { get; set; }
        public string CodTarifa { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsReserved { get; set; }
        public Nullable<bool> IsPay { get; set; }
        public string NumSecuencia { get; set; }
        public Nullable<int> DipMapId { get; set; }
        public Nullable<int> TransactionId { get; set; }
    }
}
