//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPProcinal.WCFDesAssing {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFDesAssing.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dessil", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode dessil(int tea_ext_l, int sal_ext_l, string fex_ext_l, int fun_ext_l, string fil_ext_l, int col_ext_l, int gru_ext_l, int pel_ext_l, string log_ext_l);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dessil", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Xml.XmlNode> dessilAsync(int tea_ext_l, int sal_ext_l, string fex_ext_l, int fun_ext_l, string fil_ext_l, int col_ext_l, int gru_ext_l, int pel_ext_l, string log_ext_l);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WPProcinal.WCFDesAssing.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WPProcinal.WCFDesAssing.ServiceSoap>, WPProcinal.WCFDesAssing.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode dessil(int tea_ext_l, int sal_ext_l, string fex_ext_l, int fun_ext_l, string fil_ext_l, int col_ext_l, int gru_ext_l, int pel_ext_l, string log_ext_l) {
            return base.Channel.dessil(tea_ext_l, sal_ext_l, fex_ext_l, fun_ext_l, fil_ext_l, col_ext_l, gru_ext_l, pel_ext_l, log_ext_l);
        }
        
        public System.Threading.Tasks.Task<System.Xml.XmlNode> dessilAsync(int tea_ext_l, int sal_ext_l, string fex_ext_l, int fun_ext_l, string fil_ext_l, int col_ext_l, int gru_ext_l, int pel_ext_l, string log_ext_l) {
            return base.Channel.dessilAsync(tea_ext_l, sal_ext_l, fex_ext_l, fun_ext_l, fil_ext_l, col_ext_l, gru_ext_l, pel_ext_l, log_ext_l);
        }
    }
}
